### ISSUE TITLE
Two finger scrolling not working properly

### ISSUE THREAD

**Issue by mustafa-muhammad** [kororaproject/kp#57] opened 2015-01-09 00:19 UTC
Two finger scrolling didn't work for me, so I went to touchpad configuration, and it was enabled and working on that window, I've been working on Korora for about a week and it sometimes work, but most of the time not.

**Comment by firnsy** [comment] 2015-01-09 00:27
What is your touchpad? Which DE? I can't reproduce on Gnome.

**Comment by csmart** [comment] 2015-01-09 00:32
I think this is related to #58

**Comment by mustafa-muhammad** [comment] 2015-01-09 00:42
Yes, it is related, the fix you gave me for that:
rm ~/.config/autostart/syndaemon.desktop
fixed this issue too.

**Comment by csmart** [comment] 2015-01-09 00:56
Fixed with #58

**Closed by csmart** 2015-01-09 00:56 UTC
