### ISSUE TITLE
Pharlap on Gnome 23 fails to initialize properly

### ISSUE THREAD

**Issue by exif** [kororaproject/kp#68] opened 2015-11-10 21:25 UTC
Running on my Korora Gnome 23 beta installed to a physical drive, Pharlap is failing to launch properly.

##### When run by normal user:
Pharlap window opens, but there are no contents, just a blank white surface; no initialization progress is visible and it stays in this state indefinitely; exits normally when the window is closed

Output from launch to closing the window manually when run from terminal:
```bash
[12:53 eg ~]$ pharlap
/usr/lib/python3.4/site-packages/lens/appgtk.py:28: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit2, Gio, Gtk, GObject, Gdk
```
##### When run with root privileges:
Pharlap window opens normally and displays the "Reading repository information ..." message, but does not progress beyond this point; the progress bar does not fill and there is no animation; stays in this state indefinitely and exits normally when closed

Output from launch to closing the window manually when run from terminal:
```bash
[13:07 eg ~]$ sudo pharlap
/usr/lib/python3.4/site-packages/lens/appgtk.py:28: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import WebKit2, Gio, Gtk, GObject, Gdk
Process ThreadProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/site-packages/lens/thread.py", line 86, in run
    self._thread.run()
  File "/bin/pharlap", line 60, in run
    self._config.cache = DNFCache(dnf.Base(), md_progress_cb=self._md_progress_cb)
  File "/usr/lib/python3.4/site-packages/Pharlap/dnfcache.py", line 60, in __init__
    self._db.fill_sack()
  File "/usr/lib/python3.4/site-packages/dnf/base.py", line 238, in fill_sack
    self._sack = dnf.sack.build_sack(self)
  File "/usr/lib/python3.4/site-packages/dnf/sack.py", line 84, in build_sack
    dnf.util.ensure_dir(cachedir)
  File "/usr/lib/python3.4/site-packages/dnf/util.py", line 60, in ensure_dir
    os.makedirs(dname, mode=0o755)
  File "/usr/lib64/python3.4/os.py", line 222, in makedirs
    head, tail = path.split(name)
  File "/usr/lib64/python3.4/posixpath.py", line 103, in split
    i = p.rfind(sep) + 1
AttributeError: 'YumConf' object has no attribute 'rfind'
```

This didn't happen to me on the XFCE spin; Pharlap launched properly there.

**Comment by exif** [comment] 2015-11-10 21:27
I don't seem to be able to attach labels, or maybe I am just doing something dumb

**Comment by csmart** [comment] 2015-11-10 23:32
@firnsy  ping

**Comment by firnsy** [comment] 2015-11-11 00:23
@exif with Lens applications (not that you you knew pharlap was one) one can now receive extra debugging by adding the LENS_DEBUG=1 environment variable.

It's not necessary to update this with the debug information, I'll take this issue from here

**Comment by exif** [comment] 2015-11-11 03:19
@firnsy Thanks, I'll try that next time

**Comment by firnsy** [comment] 2015-11-11 11:27
@exif, after a fresh install on real hardware i can't reproduce this bug. can you confirm you've done a full upgrade and rebooted?

**Comment by exif** [comment] 2015-11-11 17:16
@firnsy Yeah, this was after a fresh install from the beta ISO and running dnf upgrade; at this point I had made some changes to the default software configuration, but I hadn't touched any dependencies of Pharlap. I'll test the Gnome ISO on a virtual machine again and retrace my dnf transaction history to see if it's something I did.

**Comment by firnsy** [comment] 2015-11-12 09:20
Closing due to non-reproducibility.

**Closed by firnsy** 2015-11-12 09:20 UTC
Labels: 23-release
