### ISSUE TITLE
k23 beta xfce issues from exif

### ISSUE THREAD

**Issue by csmart** [kororaproject/kp#66] opened 2015-11-07 21:44 UTC
XFCE x64 test results (inside live system on a virtualbox machine)

Issue titles in quotes are application names as seen in XFCE app menu or the name of an rpm
- [x] "Audacity"
  audacity crashes in XFCE x64 after displaying  its splash screen, this is the output on crash for me: https://paste.fedoraproject.org/287961/46921265/

according to DarkEra: Audacity indeed crashes (...) also live session but then running from a usb stick
- [ ] "Bluetooth Adapters"
  "Bluetooth Adapters" application launches in a tiny window too small to display its own window title, with nothing inside of the window (though I don't have bluetooth devices on my system)
- [ ] "Firefox" (applies to all spins)
  Firefox will start disabling the preinstalled addons in FF43 because they aren't signed by Mozilla, need workaround or signed addons
- [ ] "Input Method Selector"
  IBus preferences link doesn't do anything
- [ ] Calendar functionality
  Thunderbird now includes the Lightning calendar extension by default, so since Orage is also installed there is some duplicated functionality there
- [x] "system-config-samba"
  system-config-samba crashes immediately on launch with this output: https://paste.fedoraproject.org/287987/14469270/
- [x] "Sound Converter"
  soundconverter crashes on startup with output: SoundConverter needs python-gstreamer 0.10!
- [x] "yumex-dnf"
  yumex-dnf doesn't want to quit once it's been launched and cannot be reopened once closed; a message box asking "Yum Extender is already running, do you want to quit?" comes up instead of the program itself and prevents interaction, answering yes does nothing
- [x] "slideshow timing"
  The slideshow interval is too long, reduce to 5 - 10 minutes, (one tester didn't realise it was activated as never saw the background change)

**Comment by jimkp** [comment] 2015-11-08 04:13
Audacity crashes for me too

system-config-samba crashes for me too

Sound converter crashes for me too

I couldn't reproduce the yumex-dnf problem

**Comment by jimkp** [comment] 2015-11-09 00:32
Cinnamon has the Audacity, Sound Converter & samba issues too confirming it is an application issue 

The slideshow interval is too long, reduce to 5 - 10 minutes, (one tester didn't realise it was activated as never saw the background change)

**Comment by exif** [comment] 2015-11-09 18:19
"yumex-dnf" issue is probably a duplicate of [Bug 1276109](https://bugzilla.redhat.com/show_bug.cgi?id=1276109) so cross that off for now, I'll try and confirm that soon if nobody beats me

**Comment by csmart** [comment] 2015-11-10 06:27
apart from the background, the rest seem upstream related. We should keep an eye on them, and test before 23 final images ship. @firnsy mentioned this on IRC:

[09:27:58] <firnsy> hmmm ... seems a lot of the crashes we're seeing in normal apps (mintmenu et al) is due to the mass rebuild to include -pie in the compiler
[09:28:18] <firnsy> expect many package updates in the coming days

**Comment by jimkp** [comment] 2015-11-14 02:04
latest update fixes Audacity & Sound Converter

**Comment by firnsy** [comment] 2015-11-25 01:05
@jimkp @DarkEra ... thoughts on duplicated calendar functionality in Xfce?

@csmart ... i don't think the other three are blockers for us

**Comment by jimkp** [comment] 2015-11-25 04:10
I don't see the calendar issue as a problem, we could drop Orage I guess but I would just leave it

**Comment by DarkEra** [comment] 2015-11-25 08:13
Orage is a separate desktop calendar which is also a part of Orage Panel Clock. I put it in there because i wanted to give users a choice. I remember from another Xfce project i was involved in in the past that most of the user liked to have Orage in it so it kinda became a standard for me to include it. 
There are even 3 clock applets (orage clock included) that can be added to the panel.....
T.b.h. I don't see it as a issue and would leave it as is.

**Comment by exif** [comment] 2015-11-25 14:24
For context, it wasn't a problem for me; I only included it in the list in case the change to Thunderbird hadn't been noticed. Don't let it haunt you guys or anything

**Closed** 2017-08-30 09:43 UTC
Labels: 23-release
