### ISSUE TITLE
Apps closed on reboot doesn't run on next boot

### ISSUE THREAD

**Issue by mustafa-muhammad** [kororaproject/kp#59] opened 2015-01-09 00:28 UTC
In most distributions I use, including Fedora, apps that was running before reboot starts automatically on next login ( I think this is the default for KDE), but not in Korora.

**Comment by csmart** [comment] 2015-01-09 00:36
Thanks for the report! This is by design as I think most users are happy to re-open whatever apps they use after a log in - most users will suspend otherwise which means the same apps are still running. I'll ask our KDE guy though for his thoughts..

**Comment by jimkp** [comment] 2015-01-09 00:40
KDE system settings - Startup and Shutdown - Session Management is set to Restore Manually Saved Session, change to Restore Previous Session will give you the desired behaviour.

**Comment by firnsy** [comment] 2015-01-09 00:41
Agreed with @csmart, restarting means restoring to a known clean state Enabling by default would require even more work from the user to obtain a clean start. I would be a strong -1 for such a change.

**Comment by csmart** [comment] 2015-01-09 00:43
Closing as this is by design. Thanks!

**Closed by csmart** 2015-01-09 00:43 UTC

**Comment by mustafa-muhammad** [comment] 2015-01-09 00:45
I wasn't sure if this was a design decision, both behaviours are fine for me, thank you all.
